"""Add Notice

Revision ID: 9444beb201b5
Revises: bfaab9177188
Create Date: 2026-01-30 22:11:20.516324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9444beb201b5'
down_revision = 'bfaab9177188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice')
    # ### end Alembic commands ###
